# Generated by Django 5.1.4 on 2025-01-11 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='city',
        ),
        migrations.RemoveField(
            model_name='question',
            name='state',
        ),
    ]
