# Generated by Django 5.1.4 on 2025-01-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0003_question_city_question_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='city',
        ),
        migrations.RemoveField(
            model_name='question',
            name='state',
        ),
        migrations.AlterField(
            model_name='question',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
