# Generated by Django 5.1.4 on 2025-01-12 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0002_remove_question_city_remove_question_state'),
        ('region_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region_app.city'),
        ),
        migrations.AddField(
            model_name='question',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='region_app.state'),
        ),
    ]
